### PR TITLE
Feat : Added filter

### PR DESCRIPTION
**Pull request by sushil-mod**
# Added Filter and its Functionality 

- Filter by Label and Priority
- Sort by Date

### CODE REVIEW

**Review by JantuDeb — APPROVED** [review]
This is looking good, you can good

**Comment by sushil-mod** [comment]
> This is looking good, you can good

Thank you helping me for clearing filter issue

**Review by ultronjs — APPROVED** [review]
Filter Functionality is working fine.
Filter function is also pure and clean.
Good to merge

**Comment by hussiantabha** [comment]
Looks super clean. Looks good to merge.

**Pull request merged**
